namespace Simple.ExportToExcel;

/// <summary>
/// Abstract base class that defines the visual styling applied to cells in a generated spreadsheet.
/// Concrete subclasses (<see cref="HeaderStyle"/>, <see cref="BodyStyle"/>) inherit all properties
/// and can be configured before passing them to a request.
/// </summary>
public abstract class ExcelStyle
{
    static readonly IDictionary<short, ExcelColors> _colors;

    static ExcelStyle()
    {
        _colors = new Dictionary<short, ExcelColors>(ExcelColors.ColorCollection);
    }

    /// <summary>
    /// Initializes a new instance of <see cref="ExcelStyle"/>.
    /// </summary>
    public ExcelStyle() { }

    /// <summary>
    /// The full catalogue of available spreadsheet colors, keyed by NPOI palette index.
    /// </summary>
    public static IEnumerable<ExcelColors> Colors => _colors.Values;

    /// <summary>
    /// The NPOI <see cref="ICellStyle"/> generated by the last call to <see cref="GenerateStyleObject"/>.
    /// <c>null</c> until <see cref="GenerateStyleObject"/> has been called.
    /// </summary>
    public ICellStyle CellStyle { get; private set; }

    /// <summary>
    /// Creates and configures an NPOI <see cref="XSSFCellStyle"/> from the current property values
    /// and stores it in <see cref="CellStyle"/>.
    /// </summary>
    /// <param name="workbook">The NPOI workbook used to create the cell style.</param>
    /// <returns>The configured <see cref="ICellStyle"/>.</returns>
    public ICellStyle GenerateStyleObject(in IWorkbook workbook)
    {
        XSSFCellStyle cellStyle = (XSSFCellStyle)workbook.CreateCellStyle();

        cellStyle.BorderTop = TopStyle;
        cellStyle.BorderRight = RightStyle;
        cellStyle.BorderBottom = BottomStyle;
        cellStyle.BorderLeft = LeftStyle;
        cellStyle.FillPattern = FillPattern;

        cellStyle.VerticalAlignment = VerticalAlignment;
        cellStyle.Alignment = HorizontalAlignment;

        cellStyle.SetFillForegroundColor(ForegroundColor);
        cellStyle.SetFillBackgroundColor(BackgroundColor);

        CellStyle = cellStyle;

        return cellStyle;
    }

    /// <summary>
    /// The XSSF foreground fill color. Defaults to white (RGB 255, 255, 255).
    /// Updated via <see cref="SetForegroundColor"/>.
    /// </summary>
    public XSSFColor ForegroundColor { get; private set; } = new XSSFColor(new byte[] { 255, 255, 255 }, null);

    /// <summary>
    /// The XSSF background fill color. Defaults to white (RGB 255, 255, 255).
    /// </summary>
    public XSSFColor BackgroundColor { get; private set; } = new XSSFColor(new byte[] { 255, 255, 255 }, null);

    /// <summary>
    /// Vertical cell alignment. Defaults to <see cref="NPOI.SS.UserModel.VerticalAlignment.Center"/>.
    /// </summary>
    public VerticalAlignment VerticalAlignment { get; set; } = VerticalAlignment.Center;

    /// <summary>
    /// Horizontal cell alignment. Defaults to <see cref="NPOI.SS.UserModel.HorizontalAlignment.Center"/>.
    /// </summary>
    public HorizontalAlignment HorizontalAlignment { get; set; } = HorizontalAlignment.Center;

    /// <summary>
    /// Cell fill pattern. Defaults to <see cref="NPOI.SS.UserModel.FillPattern.SolidForeground"/>.
    /// </summary>
    public FillPattern FillPattern { get; set; } = FillPattern.SolidForeground;

    /// <summary>Top border style. Defaults to <see cref="BorderStyle.Thin"/>.</summary>
    public BorderStyle TopStyle { get; set; } = BorderStyle.Thin;

    /// <summary>Right border style. Defaults to <see cref="BorderStyle.Thin"/>.</summary>
    public BorderStyle RightStyle { get; set; } = BorderStyle.Thin;

    /// <summary>Bottom border style. Defaults to <see cref="BorderStyle.Thin"/>.</summary>
    public BorderStyle BottomStyle { get; set; } = BorderStyle.Thin;

    /// <summary>Left border style. Defaults to <see cref="BorderStyle.Thin"/>.</summary>
    public BorderStyle LeftStyle { get; set; } = BorderStyle.Thin;

    /// <summary>
    /// Updates <see cref="ForegroundColor"/> from the color selected in the style picker UI.
    /// If the color index is not found in the palette the property is left unchanged.
    /// </summary>
    /// <param name="a">Event args carrying the selected color's palette index.</param>
    public void SetForegroundColor(StyleColorSelectedEventArgs a)
    {
        if (_colors.TryGetValue(a.ColorIndex, out ExcelColors color))
        {
            ForegroundColor = new XSSFColor(color.IndexedColor.RGB, null);
        }
    }

    /// <summary>
    /// Updates <see cref="HorizontalAlignment"/> from the alignment selected in the style picker UI.
    /// </summary>
    /// <param name="a">Event args carrying the selected horizontal alignment.</param>
    public void SetHorizontalAlignment(HorizontalAlignmentChangedEventArgs a) => HorizontalAlignment = a.SelectedAlignment;

    /// <summary>
    /// Updates <see cref="VerticalAlignment"/> from the alignment selected in the style picker UI.
    /// </summary>
    /// <param name="a">Event args carrying the selected vertical alignment.</param>
    public void SetVerticalAlignment(VerticalAlignmentChangedEventArgs a) => VerticalAlignment = a.SelectedAlignment;
}
